name: Example workflow for Node using Snyk
on: [pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run npm
        run: npm install 
      - name: Login
        uses: atlassian/gajira-login@master
        env:
         JIRA_BASE_URL: https://rakshitmohan99.atlassian.net
         JIRA_USER_EMAIL: rakshitmohan99@gmail.com
         JIRA_API_TOKEN: ${{ secrets.JIRA }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
         project: TEST
         issuetype: Task
         summary: |
          SCA Security Scan ${{ github.repository }} || Pull Request No: ${{github.event.number}} 
         description: |
          Security Scan for terraform pull request https://github.com/${{ github.repository }}/pull/${{github.event.number}}
         fields: '{"assignee": {"name":"rakshitmohan99@gmail.com"}}'
        
      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
         issue: ${{ steps.create.outputs.issue }}
         transition: "In progress"
    

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json-file-output=snyk.json
      - name: Snyk monitor
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: curl
        uses: wei/curl@v1
        with:
         args: --location --request POST 'https://rakshitmohan99.atlassian.net/rest/api/3/issue/${{ steps.create.outputs.issue }}/attachments' -u 'rakshitmohan99@gmail.com:${{ secrets.JIRA }}' -H 'X-Atlassian-Token:no-check' --form 'file=@"snyk.json"'
      
   
        
     
 
 

