name: Example workflow for Node using Snyk
on: [pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run npm
        run: npm install 
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json-file-output=snyk.json
      - name: Show output
        run: cat snyk.json | head -10 | tee output.json
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: output.json
